### ISSUE TITLE
2.8.1 Crashing Out

### ISSUE THREAD

**Issue by luhis** [Taritsyn/WebMarkupMin#105]
The latest version is crashing out on me in production.  Logs:
```
Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
Mar 16 19:31:55 codeGolf dotnet-codegolf[1042]: fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
Mar 16 19:31:55 codeGolf dotnet-codegolf[1042]:       An unhandled exception has occurred while executing the request.
Mar 16 19:31:55 codeGolf dotnet-codegolf[1042]: System.InvalidOperationException: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.
Mar 16 19:31:55 codeGolf dotnet-codegolf[1042]:    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.Write(Byte[] buffer, Int32 offset, Int32 count)
Mar 16 19:31:55 codeGolf dotnet-codegolf[1042]:    at System.IO.Compression.DeflateStream.PurgeBuffers(Boolean disposing)
Mar 16 19:31:55 codeGolf dotnet-codegolf[1042]:    at System.IO.Compression.DeflateStream.Dispose(Boolean disposing)
Mar 16 19:31:55 codeGolf dotnet-codegolf[1042]:    at System.IO.Stream.Close()
Mar 16 19:31:55 codeGolf dotnet-codegolf[1042]:    at System.IO.Stream.Dispose()
Mar 16 19:31:55 codeGolf dotnet-codegolf[1042]:    at System.IO.Stream.Dispose()
Mar 16 19:31:55 codeGolf dotnet-codegolf[1042]:    at System.IO.Compression.GZipStream.Dispose(Boolean disposing)
Mar 16 19:31:55 codeGolf dotnet-codegolf[1042]:    at System.IO.Stream.Close()
Mar 16 19:31:55 codeGolf dotnet-codegolf[1042]:    at System.IO.Stream.Dispose()
Mar 16 19:31:55 codeGolf dotnet-codegolf[1042]:    at WebMarkupMin.AspNetCore3.BodyWrapperStreamBase.Dispose(Boolean disposing)
Mar 16 19:31:55 codeGolf dotnet-codegolf[1042]:    at System.IO.Stream.Close()
Mar 16 19:31:55 codeGolf dotnet-codegolf[1042]:    at System.IO.Stream.DisposeAsync()
Mar 16 19:31:55 codeGolf dotnet-codegolf[1042]: --- End of stack trace from previous location where exception was thrown ---
```
I'll see if i can get this happening locally, but hopefully you know what this means.

My tests aren't picking it up, but if you visit https://codegolf.club you see the stream being cut off.

**Comment by Taritsyn** [comment]
Hello, Matt!

Thanks for information! This error is fixed in [version 2.8.2](https://github.com/Taritsyn/WebMarkupMin/releases/tag/v2.8.2).
