### ISSUE TITLE
InvalidOperationException: Can not apply markup minification to text content, that was encoded in the 'gzip' format.

### ISSUE THREAD

**Issue by sean-thorburn** [Taritsyn/WebMarkupMin#128]
I randomly get this in my React projects, is there a way to prevent it? I think its trying to minifi index.html from ClientApp/public.

Sometimes I just need to make a change to the index.html file and it goes away, other times it doesn't.

`System.InvalidOperationException: Can not apply markup minification to text content, that was encoded in the 'gzip' format.
   at WebMarkupMin.AspNetCore5.BodyWrapperStreamBase.Initialize()
   at WebMarkupMin.AspNetCore5.BodyWrapperStreamBase.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.CopyToAsyncCore(Stream destination, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SpaServices.Extensions.Proxy.SpaProxy.CopyProxyHttpResponse(HttpContext context, HttpResponseMessage responseMessage, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SpaServices.Extensions.Proxy.SpaProxy.PerformProxyRequest(HttpContext context, HttpClient httpClient, Task`1 baseUriTask, CancellationToken applicationStoppingToken, Boolean proxy404s)
   at Microsoft.AspNetCore.Builder.SpaProxyingExtensions.<>c__DisplayClass2_0.<<UseProxyToSpaDevelopmentServer>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at WebMarkupMin.AspNetCore5.WebMarkupMinMiddleware.ProcessAsync(HttpContext context, Boolean useMinification, Boolean useCompression)
   at WebMarkupMin.AspNetCore5.WebMarkupMinMiddleware.ProcessAsync(HttpContext context, Boolean useMinification, Boolean useCompression)
   at WebMarkupMin.AspNetCore5.WebMarkupMinMiddlewareBase.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)`

**Comment by Taritsyn** [comment]
Hello, Sean!

In your case, GZip compression is performed before a HTML minification. How do you perform a HTTP compression?

**Comment by sean-thorburn** [comment]
It seems to be coming from Node.js.

I think I can solve this by excluding React/Node.js, and just processing the MVC Razor views.

Is it possible to exclude certain URLs from WebMarkupMin?

**Comment by Taritsyn** [comment]
> Is it possible to exclude certain URLs from WebMarkupMin?

See the [“ASP.NET Extensions > Managers and options”](https://github.com/Taritsyn/WebMarkupMin/wiki/ASP.NET-Extensions#managers-and-options) subsection of documentation.

**Comment by sean-thorburn** [comment]
Thanks, this solved my problem. I added the solution to stackoverflow as I could not find anything similar with a Google search. https://stackoverflow.com/questions/66934081/webmarkupmin-razor-react-can-not-apply-markup-minification-to-text-content/66934082#66934082
