### ISSUE TITLE
An unhandled exception has occurred. 

### ISSUE THREAD

**Issue by JohnBergman** [Taritsyn/WebMarkupMin#39]
While I agree, this appears to be malformed html/output; the package should not throw an exception and provide a yellow screen of death, instead it should simply not minify things.  Here is the stack trace

Exception information: 
    Exception type: MarkupMinificationException 
    Exception message: Category: JS_MINIFICATION_ERROR
Message: Unterminated string literal.
File: /a/us-tx/climbing/top-4-climbing-spots-in-austin/
Line number: 2001
Column number: 11
Source fragment:

Line 2001:   <script>
---------------------^

   at WebMarkupMin.Core.Loggers.ThrowExceptionLogger.Error(String category, String message, String filePath, Int32 lineNumber, Int32 columnNumber, String sourceFragment)
   at WebMarkupMin.Core.GenericHtmlMinifier.ProcessEmbeddedScriptContent(MarkupParsingContext context, String content, String contentType)
   at WebMarkupMin.Core.GenericHtmlMinifier.EmbeddedCodeHandler(MarkupParsingContext context, String code)
   at WebMarkupMin.Core.Parsers.HtmlParser.ProcessEmbeddedCode()
   at WebMarkupMin.Core.Parsers.HtmlParser.Parse(String content)
   at WebMarkupMin.Core.GenericHtmlMinifier.Minify(String content, String fileContext, Encoding encoding, Boolean generateStatistics)
   at WebMarkupMin.AspNet4.Common.MarkupMinificationFilterStream.Close()
   at ClientDependency.Core.Module.ResponseFilterStream.Close() in X:\Projects\ClientDependency\ClientDependency\ClientDependency.Core\Module\ResponseFilterStream.cs:line 313
   at System.Web.HttpWriter.FilterIntegrated(Boolean finalFiltering, IIS7WorkerRequest wr)
   at System.Web.HttpResponse.FilterOutput()
   at System.Web.HttpApplication.CallFilterExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by Taritsyn** [comment]
Hello, John!

I recommend you to read the discussion of [“drop minification in case of errors”](https://github.com/Taritsyn/WebMarkupMin/issues/16) issue.

**Comment by JohnBergman** [comment]
I get the idea of setting a default logger, but I do not see exactly where that property exists, it does not appear to be off of the WebMarkupMinConfiguration object, nor the IHtmlMinificationManagers.  Any pointers would be appreciated.

**Comment by Taritsyn** [comment]
> Any pointers would be appreciated.

It seems, that you have not read the discussion. Here is my answer from the discussion:

Replace a `ThrowExceptionLogger` to `NullLogger` or your custom logger (see [“Loggers”](https://github.com/Taritsyn/WebMarkupMin/wiki/Loggers) section of the documentation).

In [ASP.NET 4.X Extensions](https://github.com/Taritsyn/WebMarkupMin/wiki/ASP.NET-4.X-Extensions) this is done in the following way:

``` csharp
DefaultLogger.Current = new MyLogger();
```

In [ASP.NET Core 1.X Middleware](https://github.com/Taritsyn/WebMarkupMin/wiki/WebMarkupMin:-ASP.NET-Core-1.X) is done as follows:

``` csharp
services.AddSingleton<WebMarkupMin.Core.Loggers.ILogger, MyLogger>();
```

**Comment by JohnBergman** [comment]
OK, I found it, the problem was I missed the namespace "WebMarkupMin.Core.Loggers", until I reflectored some of the assemblies to try to see how that was used.

Might be worth added a note to the docs.

**Comment by Taritsyn** [comment]
`DefaultLogger` is a class from the `WebMarkupMin.AspNet4.Common` namespace.

**Comment by JohnBergman** [comment]
NullLogger is in WebMarkupMin.Core.Loggers, sorry for not being completely clear :-)

**Comment by Taritsyn** [comment]
Made changes in sections of the documentation: [“Loggers”](https://github.com/Taritsyn/WebMarkupMin/wiki/Loggers) and [“ASP.NET 4.X Extensions”](https://github.com/Taritsyn/WebMarkupMin/wiki/ASP.NET-4.X-Extensions). In addition, there are also tooltips, that appear when hovering over a class name.

**Comment by rahulbpatel** [comment]
I know this is an old, closed, issue but we just ran into a flood of these errors.  Out of curiosity how is it that WebMarkupMin is being invoked by ClientDependency?  We are running Umbraco v7 but I can't find anywhere how it is wired up.  I don't see it in `.config` files and I don't see how it is registered.

```
at WebMarkupMin.AspNet4.Common.MarkupMinificationFilterStream.Close()
at ClientDependency.Core.Module.ResponseFilterStream.Close() in X:\Projects\ClientDependency\ClientDependency\ClientDependency.Core\Module\ResponseFilterStream.cs:line 313
```

**Comment by Taritsyn** [comment]
Hello, Rahul!

What WebMarkupMin's packages do you have installed?

**Comment by rahulbpatel** [comment]
Hi @Taritsyn, 

This is what's in `packages.config`:

```
  <package id="WebMarkupMin.AspNet.Common" version="2.4.0" targetFramework="net471" />
  <package id="WebMarkupMin.AspNet4.Common" version="2.4.0" targetFramework="net471" />
  <package id="WebMarkupMin.AspNet4.Mvc" version="2.4.0" targetFramework="net471" />
  <package id="WebMarkupMin.Core" version="2.4.0" targetFramework="net471" />
```

**Comment by rahulbpatel** [comment]
This is what my stack trace looks like:

```
   at WebMarkupMin.Core.Loggers.ThrowExceptionLogger.Error(String category, String message, String filePath, Int32 lineNumber, Int32 columnNumber, String sourceFragment)
   at WebMarkupMin.Core.GenericHtmlMinifier.ProcessEmbeddedScriptContent(MarkupParsingContext context, String content, String contentType)
   at WebMarkupMin.Core.GenericHtmlMinifier.EmbeddedCodeHandler(MarkupParsingContext context, String code)
   at WebMarkupMin.Core.Parsers.HtmlParser.ProcessEmbeddedCode()
   at WebMarkupMin.Core.Parsers.HtmlParser.Parse(String content)
   at WebMarkupMin.Core.GenericHtmlMinifier.Minify(String content, String fileContext, Encoding encoding, Boolean generateStatistics)
   at WebMarkupMin.AspNet4.Common.MarkupMinificationFilterStream.Close()
   at ClientDependency.Core.Module.ResponseFilterStream.Close() in C:\Users\Shannon\Documents\_Projects\ClientDependency\ClientDependency\ClientDependency.Core\Module\ResponseFilterStream.cs:line 313
   at System.Web.HttpWriter.FilterIntegrated(Boolean finalFiltering, IIS7WorkerRequest wr)
   at System.Web.HttpResponse.FilterOutput()
   at System.Web.HttpApplication.CallFilterExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

**Comment by Taritsyn** [comment]
> &lt;package id="WebMarkupMin.AspNet4.Mvc" version="2.4.0" targetFramework="net471" />

`MinifyHtmlAttribute`, `MinifyXhtmlAttribute` or `MinifyXmlAttribute` attributes are used somewhere in your code?

**Comment by Taritsyn** [comment]
In general, I recommend that you re-read the following sections of documentation: [“ASP.NET Extensions”](https://github.com/Taritsyn/WebMarkupMin/wiki/ASP.NET-Extensions), [“ASP.NET 4.X Extensions”](https://github.com/Taritsyn/WebMarkupMin/wiki/ASP.NET-4.X-Extensions) and [“ASP.NET 4.X MVC”](https://github.com/Taritsyn/WebMarkupMin/wiki/ASP.NET-4.X-MVC).

**Comment by rahulbpatel** [comment]
It's not in our code base, I've looked everywhere.  Searched the Umbraco CMS and ClientDependency Github repos with no luck.
